version: '3.2'

volumes:
  tmp-data:
  postgres:

services:
  app:
    image: motorcode/chat:0.0.1
    working_dir: /src
    ports:
      -
        target: 3005
        published: 3005
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MIGRATIONS_PATH: ./migrations
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    networks:
      - test_app
    depends_on:
      - postgres
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  
  haproxy:
    build:
      context: ../..
      dockerfile: ./images/haproxy/Dockerfile
    volumes:
      - ../configs/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - '80:80'
    links:
      - app

  postgres:
    image: motorcode/chat-postgres:0.0.1
    restart: unless-stopped
    environment:
      POSTGERS_USER: chatapp
      POSTGERS_NAME: chatapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /storage/postgres-data
    volumes:
      - postgres:/storage/postgres-data
    ports:
      - "5433:5433"
    networks:
      - test_app

networks:
  test_app:
