version: '3.2'

volumes:
  tmp-data:
  postgres:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    command: ./golang-developer-test-task
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    networks:
      - test_app
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_DB: chatapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /storage/postgres-data
    volumes:
      - postgres:/storage/postgres-data
    ports:
      - "5433:5433"
    networks:
      - test_app


networks:
  test_app:
