version: '3.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    command: ./golang-developer-test-task
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    networks:
      - test_app
    depends_on:
      - redis

  redis:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgers:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - "5432":"5432"
    networks:
      - test_app


networks:
  test_app:
