version: '3.2'

volumes:
  tmp-data:
  postgres:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    command: ./golang-developer-test-task
    ports:
      - "3005:3005"
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    networks:
      - test_app
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_DB: chatapp
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /storage/postgres-data
    volumes:
      - postgres:/storage/postgres-data
    ports:
      - "5433:5433"
    networks:
      - test_app
  
  influxdb:
    image: influxdb
    ports:
      - 8082:8082
      - 8086:8086
      - 8089:8089
    volumes:
      - ./configs/influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./configs/influx/prometheus.iql:/docker-entrypoint-initdb.d/prometheus.iql:ro
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=prometheus
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_READ_USER=grafana
      - INFLUXDB_READ_USER_PASSWORD=password
  prometheus:
    image: prom/prometheus:master
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--log.level=debug",
      "--storage.tsdb.path=/prometheus",
      "--storage.tsdb.retention=1h",
      "--web.enable-admin-api",
    ]
    depends_on:
      - prometheus-influxdb-adapter

  prometheus-influxdb-adapter: 
    image: kaorimatz/prometheus-influxdb-adapter
    ports: 
      - 9201:9201
    environment:
      - WRITE_INFLUXDB_URL=http://prometheus:password@influxdb:8086
    command: [
      "--log.level=debug",
      "--read.influxdb.field=max_over_time:max",
      "--read.influxdb.field=min_over_time:min",
      "--read.influxdb.field=sum_over_time:sum",
      "--read.influxdb.field=mean",
      "--read.influxdb.retention-policy=1h:1h",
      "--read.influxdb.retention-policy=5m:5m",
      "--read.influxdb.retention-policy=1m",
      "--read.influxdb.rpc-address=influxdb:8082",
    ]
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:master
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources:ro
networks:
  test_app:
