 
global:
    scrape_interval: 1s
scrape_configs:
    - job_name: grafana
      static_configs:
        - targets:
          - grafana:3000
    - job_name: influxdb
      static_configs:
        - targets:
          - influxdb:8086
    - job_name: prometheus
      static_configs:
        - targets:
          - prometheus:9090
    - job_name: prometheus-influxdb-adapter
      static_configs:
        - targets:
          - prometheus-influxdb-adapter:9201
remote_write:
    - url: http://prometheus-influxdb-adapter:9201/write
remote_read:
    - url: http://prometheus-influxdb-adapter:9201/read